In [2]:
# !pip install pandas
# https://colab.research.google.com/drive/1hRMpXIXgUF6ITL0OYgrmsdQFGwPYPGqx?usp=sharing

In [3]:

import pandas as pd
name = pd.Series(["Om","Jai","Jagdish","Mahesh"])
print(name,type(name))
64

0         Om
1        Jai
2    Jagdish
3     Mahesh
dtype: object <class 'pandas.core.series.Series'>

64

In [4]:
name.shape

(4,)

In [5]:
name.ndim

1

In [6]:
name.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
name.values

array(['Om', 'Jai', 'Jagdish', 'Mahesh'], dtype=object)

In [8]:
len(name)

4

In [9]:
df = pd.DataFrame({"a":[100,200,300,600],"b":[400,500,600,600],"c":[700,800,900,400],"d":[1000,1100,1200,100],})
df

     a    b    c     d
0  100  400  700  1000
1  200  500  800  1100
2  300  600  900  1200
3  600  600  400   100

In [10]:
df.iloc[1]

a     200
b     500
c     800
d    1100
Name: 1, dtype: int64

In [11]:
df.iloc[0:2:]

     a    b    c     d
0  100  400  700  1000
1  200  500  800  1100

In [12]:
df.index = ["w", "x", "y", "z"]
df

     a    b    c     d
w  100  400  700  1000
x  200  500  800  1100
y  300  600  900  1200
z  600  600  400   100

In [13]:
df.loc["x"::2]

     a    b    c     d
x  200  500  800  1100
z  600  600  400   100

In [14]:
df.loc[::2]

     a    b    c     d
w  100  400  700  1000
y  300  600  900  1200

In [15]:
import seaborn as sns
import pandas as pd 

# df = pd.read_csv
# df = pd.read_json
# df = pd.read_html
# df = pd.read_excel

df = pd.read_csv(r"/Users/ravimahor/Downloads/titanic.csv")
df
# data_titanic = sns.load_dataset('titanic')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [16]:
df.shape

(891, 15)

In [17]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [18]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [19]:
df.size

13365

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB

In [21]:
df.dtypes

survived         int64
pclass           int64
sex             object
age            float64
sibsp            int64
parch            int64
fare           float64
embarked        object
class           object
who             object
adult_male        bool
deck            object
embark_town     object
alive           object
alone             bool
dtype: object

In [22]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [23]:
df.describe(include='object')

         sex embarked  class  who deck  embark_town alive
count    891      889    891  891  203          889   891
unique     2        3      3    3    7            3     2
top     male        S  Third  man    C  Southampton    no
freq     577      644    491  537   59          644   549

In [24]:
df.describe(include='all')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
survived,891.0,NaN,NaN,NaN,0.383838,0.486592,0.0,0.0,0.0,1.0,1.0
pclass,891.0,NaN,NaN,NaN,2.308642,0.836071,1.0,2.0,3.0,3.0,3.0
sex,891,2,male,577,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,714.0,NaN,NaN,NaN,29.699118,14.526497,0.42,20.125,28.0,38.0,80.0
sibsp,891.0,NaN,NaN,NaN,0.523008,1.102743,0.0,0.0,0.0,1.0,8.0
parch,891.0,NaN,NaN,NaN,0.381594,0.806057,0.0,0.0,0.0,0.0,6.0
fare,891.0,NaN,NaN,NaN,32.204208,49.693429,0.0,7.9104,14.4542,31.0,512.3292
embarked,889,3,S,644,NaN,NaN,NaN,NaN,NaN,NaN,NaN
class,891,3,Third,491,NaN,NaN,NaN,NaN,NaN,NaN,NaN
who,891,3,man,537,NaN,NaN,NaN,NaN,NaN,NaN,NaN
adult_male,891,2,True,537,NaN,NaN,NaN,NaN,NaN,NaN,NaN
deck,203,7,C,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN
embark_town,889,3,Southampton,644,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alive,891,2,no,549,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alone,891,2,True,537,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [27]:
df.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [28]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [29]:
df.tail(30)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
861,0,2,male,21.0,1,0,11.5000,S,Second,man,True,NaN,Southampton,no,False
862,1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
864,0,2,male,24.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
865,1,2,female,42.0,0,0,13.0000,S,Second,woman,False,NaN,Southampton,yes,True
866,1,2,female,27.0,1,0,13.8583,C,Second,woman,False,NaN,Cherbourg,yes,False
867,0,1,male,31.0,0,0,50.4958,S,First,man,True,A,Southampton,no,True
868,0,3,male,NaN,0,0,9.5000,S,Third,man,True,NaN,Southampton,no,True
869,1,3,male,4.0,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
870,0,3,male,26.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True
874,1,2,female,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
876,0,3,male,20.0,0,0,9.8458,S,Third,man,True,NaN,Southampton,no,True
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [30]:
df.iloc[20:51:1]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
25,1,3,female,38.0,1,5,31.3875,S,Third,woman,False,NaN,Southampton,yes,False
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
28,1,3,female,NaN,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
29,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
30,0,1,male,40.0,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
32,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
33,0,2,male,66.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
34,0,1,male,28.0,1,0,82.1708,C,First,man,True,NaN,Cherbourg,no,False
35,0,1,male,42.0,1,0,52.0000,S,First,man,True,NaN,Southampton,no,False
36,1,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,yes,True
37,0,3,male,21.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
39,1,3,female,14.0,1,0,11.2417,C,Third,child,False,NaN,Cherbourg,yes,False
40,0,3,female,40.0,1,0,9.4750,S,Third,woman,False,NaN,Southampton,no,False
41,0,2,female,27.0,1,0,21.0000,S,Second,woman,False,NaN,Southampton,no,False
42,0,3,male,NaN,0,0,7.8958,C,Third,man,True,NaN,Cherbourg,no,True
43,1,2,female,3.0,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
44,1,3,female,19.0,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
45,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
46,0,3,male,NaN,1,0,15.5000,Q,Third,man,True,NaN,Queenstown,no,False
47,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
48,0,3,male,NaN,2,0,21.6792,C,Third,man,True,NaN,Cherbourg,no,False
49,0,3,female,18.0,1,0,17.8000,S,Third,woman,False,NaN,Southampton,no,False
50,0,3,male,7.0,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False

In [31]:
df.loc[::,"age":"fare":1]
# df.loc[row(start,stop,step),colum(start,stop,step)]

      age  sibsp  parch     fare
0    22.0      1      0   7.2500
1    38.0      1      0  71.2833
2    26.0      0      0   7.9250
3    35.0      1      0  53.1000
4    35.0      0      0   8.0500
..    ...    ...    ...      ...
886  27.0      0      0  13.0000
887  19.0      0      0  30.0000
888   NaN      1      2  23.4500
889  26.0      0      0  30.0000
890  32.0      0      0   7.7500

[891 rows x 4 columns]

In [32]:
df.iloc[20:51:,3:7:1]

     age  sibsp  parch      fare
20  35.0      0      0   26.0000
21  34.0      0      0   13.0000
22  15.0      0      0    8.0292
23  28.0      0      0   35.5000
24   8.0      3      1   21.0750
25  38.0      1      5   31.3875
26   NaN      0      0    7.2250
27  19.0      3      2  263.0000
28   NaN      0      0    7.8792
29   NaN      0      0    7.8958
30  40.0      0      0   27.7208
31   NaN      1      0  146.5208
32   NaN      0      0    7.7500
33  66.0      0      0   10.5000
34  28.0      1      0   82.1708
35  42.0      1      0   52.0000
36   NaN      0      0    7.2292
37  21.0      0      0    8.0500
38  18.0      2      0   18.0000
39  14.0      1      0   11.2417
40  40.0      1      0    9.4750
41  27.0      1      0   21.0000
42   NaN      0      0    7.8958
43   3.0      1      2   41.5792
44  19.0      0      0    7.8792
45   NaN      0      0    8.0500
46   NaN      1      0   15.5000
47   NaN      0      0    7.7500
48   NaN      2      0   21.6792
49  18.0      1      0   17.8000
50   7.0      4      1   39.6875

In [33]:
df.isnull().sum()
# df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [34]:
df.isnull().sum().sum()
# df.isna().sum()

np.int64(869)

In [35]:
df.age.mean()

np.float64(29.69911764705882)

In [36]:
df.age.median()

28.0

In [37]:
df.sex.value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [38]:
df.sex.value_counts(dropna=False)

sex
male      577
female    314
Name: count, dtype: int64

In [39]:
df.sex.unique()

array(['male', 'female'], dtype=object)

In [40]:
df.sex.nunique()

2

In [41]:
print(df.sex.value_counts().loc['male']/len(df)*100)

64.75869809203144

In [42]:
print(df.sex.value_counts().iloc[0]/len(df)*100)

64.75869809203144

In [43]:
df.embark_town.mode()

0    Southampton
Name: embark_town, dtype: object

In [44]:
df.embark_town.value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [45]:
df[df.duplicated()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
47,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
76,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
77,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
87,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
95,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,0,3,male,26.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True

In [46]:
df.drop(columns=['embarked'])

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Third,man,True,NaN,Queenstown,no,True

In [47]:
df.drop(columns = ['embarked','class','who','adult_male','deck','alive','alone'],axis=1,inplace=True)

In [49]:
pd.crosstab(df.sex,df.survived,normalize=True)*100

survived          0          1
sex
female     9.090909  26.150393
male      52.525253  12.233446

In [80]:
df['embark_town'] = df['embark_town'].map({"Southampton":0,"Cherbourg":1,"Queenstown":2})
df

     survived  pclass     sex   age  sibsp  parch     fare  embark_town
0           0       3    male  22.0      1      0   7.2500          0.0
1           1       1  female  38.0      1      0  71.2833          1.0
2           1       3  female  26.0      0      0   7.9250          0.0
3           1       1  female  35.0      1      0  53.1000          0.0
4           0       3    male  35.0      0      0   8.0500          0.0
..        ...     ...     ...   ...    ...    ...      ...          ...
886         0       2    male  27.0      0      0  13.0000          0.0
887         1       1  female  19.0      0      0  30.0000          0.0
888         0       3  female   NaN      1      2  23.4500          0.0
889         1       1    male  26.0      0      0  30.0000          1.0
890         0       3    male  32.0      0      0   7.7500          2.0

[891 rows x 8 columns]

In [81]:
df['sex'] = df['sex'].map({"male":1,"female":0})
df

     survived  pclass  sex   age  sibsp  parch     fare  embark_town
0           0       3    1  22.0      1      0   7.2500          0.0
1           1       1    0  38.0      1      0  71.2833          1.0
2           1       3    0  26.0      0      0   7.9250          0.0
3           1       1    0  35.0      1      0  53.1000          0.0
4           0       3    1  35.0      0      0   8.0500          0.0
..        ...     ...  ...   ...    ...    ...      ...          ...
886         0       2    1  27.0      0      0  13.0000          0.0
887         1       1    0  19.0      0      0  30.0000          0.0
888         0       3    0   NaN      1      2  23.4500          0.0
889         1       1    1  26.0      0      0  30.0000          1.0
890         0       3    1  32.0      0      0   7.7500          2.0

[891 rows x 8 columns]

https://colab.research.google.com/drive/1PEnUoqP-OeAw8pbAvEKhkzOr1UObrfIL?usp=sharing

In [ ]:
data_data =

https://colab.research.google.com/drive/10nCbUcNHO1nP3xpvxIlJLI8tvCC4y-Sx?usp=sharing

https://colab.research.google.com/drive/1po2DopKekjseyRAU4KLBDAah-Jx0Rx-o?usp=sharing